server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**

        - id: invoice-service
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/invoices/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

      discovery:
        locator:
          enabled: true   # 🔥 FIXED POSITION

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
