server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: rohan911

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
